import { ArrowUpRight, ArrowDown, ArrowRight, Layers3, Focus, Sparkles } from 'lucide-react';
import { products } from '@/lib/products';

function Brand() { return <a href="#" className="brand" aria-label="Odivon ana sayfa"><span className="brand-symbol" aria-hidden="true"/><span>odivon<span className="brand-dot">.</span></span></a>; }
export default function Home() {
  return <>
    <a className="skip-link" href="#main">İçeriğe geç</a>
    <header className="header wrap"><Brand/><nav aria-label="Ana menü"><a href="#urunler">Ürünler</a><a href="#odivon">Odivon hakkında</a></nav><a className="header-cta" href="#yaklasim">Bizi keşfet <ArrowUpRight size={17}/></a></header>
    <main id="main">
      <section className="hero wrap" aria-labelledby="hero-title">
        <div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> FİKİRDEN ÜRÜNE, ODIVON.</div><h1 id="hero-title">Bir fikir.<br/>Bir adım ötesi.<br/><span>Yeni olasılıklar.</span></h1><p>Hayatı ve işi kolaylaştıran dijital ürünler geliştiriyoruz. Farklı ihtiyaçları, iyi düşünülmüş yazılımlarla buluşturuyoruz.</p><div className="hero-actions"><a className="button" href="#urunler">Ürünleri keşfet <ArrowUpRight size={19}/></a><a className="text-link" href="#odivon">Odivon’u tanı <ArrowRight size={18}/></a></div></div>
        <div className="hero-art"><div className="art-top"><span>ODIVON EVRENİ</span><span>01 — ∞</span></div><div className="art-image" role="img" aria-label="Yeni olasılıkları temsil eden mor Odivon halkası"/><div className="art-bottom"><span>Farklı ürünler.<br/><strong>Aynı merak.</strong></span><span className="art-arrow"><ArrowUpRight size={28}/></span></div></div>
      </section>
      <div className="manifesto-line wrap"><span>Yazılımla başlayan, hayatın içine uzanan fikirler.</span><a href="#odivon" aria-label="Odivon hakkında bölümüne ilerle"><ArrowDown size={19}/></a></div>
      <section id="odivon" className="about wrap"><div className="section-label"><span>01 / BİZ KİMİZ</span><span className="little-line"/></div><div><h2>Tek bir alana değil,<br/><span>iyi bir fikre inanıyoruz.</span></h2><div className="about-bottom"><p>Her ihtiyacın kendine özgü bir hikâyesi var. Odivon, bu hikâyeleri anlayıp kullanımı kolay, anlamlı dijital ürünlere dönüştürmek için doğdu.</p><p>Merkezimizde yazılım var. Odağımızda ise onunla yapabileceklerimiz: işleri sadeleştirmek, zaman kazandırmak ve yeni olanaklar yaratmak.</p></div></div></section>
      <section id="urunler" className="products-section"><div className="wrap"><div className="section-label">02 / ÜRÜNLERİMİZ</div><div className="section-heading"><h2>Bir marka.<br/><span>Pek çok olasılık.</span></h2><p>Farklı ihtiyaçlara odaklanan ürünler.<br/>Hepsinin arkasında Odivon.</p></div>{products.length ? <div className="product-grid">{products.map(product=><a key={product.name} className="product-card" href={product.url}><span>{product.category}</span><h3>{product.name}</h3><p>{product.description}</p><span className="text-link">Ürüne git <ArrowUpRight size={18}/></span></a>)}</div> : <div className="coming-soon"><span className="coming-icon"><Layers3 size={31} strokeWidth={1.4}/></span><div><span className="pill"><span className="status-dot"/> YAKINDA</span><h3>Yeni fikirler üzerinde çalışıyoruz.</h3><p>Ürünlerimiz hazır oldukça burada yerini alacak.<br/>Bu, Odivon’un ilk adımı.</p></div><span className="coming-number" aria-hidden="true">0 → 1</span></div>}</div></section>
      <section id="yaklasim" className="approach wrap"><div className="section-label">03 / YAKLAŞIMIMIZ</div><div className="section-heading"><h2>İyi yazılım.<br/><span>Gerçek bir karşılık.</span></h2><p>Ürettiğimiz her şeyde<br/>aynı üç ilkeyi önemsiyoruz.</p></div><div className="principles">{[{n:'01',icon:<Focus/>,title:'İhtiyaçtan başlarız.',text:'Önce çözülmesi gereken problemi anlarız. Teknolojiyi, doğru çözümü üretmek için kullanırız.'},{n:'02',icon:<Layers3/>,title:'Karmaşıklığı sadeleştiririz.',text:'Güçlü bir ürünün kullanımı kolay olmalı. Her ayrıntıyı daha anlaşılır bir deneyim için düşünürüz.'},{n:'03',icon:<Sparkles/>,title:'Gelişmeye devam ederiz.',text:'Yayınlamak bir başlangıç. Geri bildirimlerden öğrenir, ürünlerimizi ihtiyaçlarla birlikte geliştiririz.'}].map(item=><article key={item.n}><div className="principle-top">{item.icon}<span>{item.n}</span></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
      <section className="closing wrap"><span className="eyebrow">MERAKLA BAŞLAR. YAZILIMLA HAYAT BULUR.</span><h2>Bir sonraki olasılık,<br/><span>burada başlıyor.</span></h2><a className="button" href="#urunler">Odivon ürünleri <ArrowUpRight size={19}/></a></section>
    </main><footer className="footer wrap"><Brand/><span>© {new Date().getFullYear()} Odivon</span><a href="#">Başa dön <ArrowUpRight size={16}/></a></footer>
  </>;
}
