'use client';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Layers3, Play, FileText, X, Check, Flag, Receipt, Dumbbell, Activity, Workflow, Sprout, Waves, GraduationCap, Braces, ShoppingBag, Heart, PawPrint } from 'lucide-react';
import { usePreferences } from '@/components/site-shell';
import { products, type Product } from '@/lib/products';
import { ui } from '@/lib/ui-messages';
import { Dialog, DialogTrigger, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
const productIcons = {golf:Flag,invoice:Receipt,gym:Dumbbell,apm:Activity,integration:Workflow,farm:Sprout,spa:Waves,school:GraduationCap,api:Braces,b2c:ShoppingBag,together:Heart,vet:PawPrint};
function ProductCard({product}:{product:Product}) {
 const {locale}=usePreferences();const u=ui[locale];const Icon=productIcons[product.symbol];
 return <article className="catalogue-card" data-product={product.symbol}><div className="card-art"><Icon size={56} strokeWidth={1}/><span className="product-art-name" aria-hidden="true">{product.name.replace('Odivon','')}</span><span className="pill">{product.status==='available'?u.live:u.preview}</span></div><div className="card-body"><span className="card-category">{product.category[locale]}</span><h2>{product.name}</h2><p>{product.description[locale]}</p><div className="card-actions"><Dialog><DialogTrigger className="outline-button"><FileText size={17}/>{u.details}</DialogTrigger><DialogContent className="product-dialog" showCloseButton={false}><DialogClose className="dialog-close" aria-label={u.close}><X size={20}/></DialogClose><span className="card-category">{product.category[locale]}</span><DialogTitle className="product-dialog-title">{product.name}</DialogTitle><DialogDescription className="product-dialog-description">{product.details[locale]}</DialogDescription>{product.demoUrl&&<a className="button" href={product.demoUrl} target="_blank" rel="noopener noreferrer">{u.demo}<ArrowUpRight size={18}/></a>}</DialogContent></Dialog>{product.demoUrl?<a className="button" href={product.demoUrl} target="_blank" rel="noopener noreferrer"><Play size={16}/>{u.demo}</a>:<button className="button" disabled>{u.demoUnavailable}</button>}</div></div></article>;
}
export default function ProductsPage(){
 const {locale}=usePreferences();const u=ui[locale];
 return <main id="main" className="catalogue-page wrap"><div className="breadcrumbs"><Link href="/">{u.home}</Link><ArrowRight size={13}/><span>{u.catalogue}</span></div><section className="catalogue-intro"><div className="eyebrow"><span className="status-dot"/>ODIVON / {u.catalogue.toLocaleUpperCase(locale)}</div><h1>{u.catalogueTitle}</h1><p>{u.catalogueText}</p></section><section aria-label={u.catalogue} className="catalogue-grid">{products.length?products.map(p=><ProductCard key={p.id} product={p}/>):<article className="catalogue-card upcoming-card"><div className="card-art"><Layers3 size={66} strokeWidth={1}/><span className="pill"><span className="status-dot"/>{u.preview}</span><span className="card-watermark" aria-hidden="true">odivon.</span></div><div className="card-body"><span className="card-category">ODIVON</span><h2>{u.emptyTitle}</h2><p>{u.emptyText}</p><div className="card-actions"><button className="outline-button" disabled aria-describedby="availability-note"><FileText size={17}/>{u.details}</button><button className="button" disabled aria-describedby="availability-note"><Play size={16}/>{u.demo}</button></div><p className="availability-note" id="availability-note">{u.emptyNote}</p></div></article>}</section><section className="trust-section"><div className="trust-heading"><h2>{u.trustTitle}</h2><p>{u.trustText}</p></div><div className="trust-grid">{u.trustItems.map(([title,text])=><article key={title}><Check size={20}/><h3>{title}</h3><p>{text}</p></article>)}</div></section></main>;
}

