export const messages = {
 tr: {
  lang:'Dil seçimi', nav:'Ana menü', home:'Odivon ana sayfa', skip:'İçeriğe geç', products:'Ürünler', about:'Odivon hakkında', approach:'Yaklaşımımız', explore:'Ürünleri keşfet', meet:'Odivon’u tanı',
  eyebrow:'TEK MARKA. FARKLI DÜNYALAR. GERÇEK ÜRÜNLER.', hero:['İşin değişir.','Hayat değişir.','Yazılımla.'], intro:'Finanstan eğitime, işletme yönetiminden günlük yaşama. Odivon, gerçek ihtiyaçlar için çalışan dijital ürünler geliştirir.', scroll:'KEŞFETMEYE DEVAM ET', orbit:'FİKİRDEN ÜRÜNE', infinite:'Sınırsız merak.',
  strip:['Gerçek ihtiyaca odaklan.','İyi deneyim tasarla.','Ürünü kullanıma aç.'], aboutLabel:'01 — ODIVON’U TANI', aboutTitle:['Bir sektöre sığmaz.','İhtiyaca odaklanır.'], aboutText:'Odivon, birbirinden farklı alanlara odaklanan bir yazılım ürünleri ailesi. Her ürün kendi kullanıcısının işini anlamak ve günlük akışını kolaylaştırmak için geliştiriliyor.', aboutNote:'Farklı alanlar. Odaklı ürünler. Tek bir Odivon.',
  productLabel:'02 — ÜRÜN EVRENİ', productTitle:['Farklı dünyalar.','Aynı imza.'], productText:'Her ürün kendi problemine odaklanır. Hepsi aynı merak ve sade bir deneyim anlayışıyla hayat bulur.', soon:'YAKINDA', soonTitle:'Sıradaki olasılık\nhenüz yazılıyor.', soonText:'Yeni fikirler üzerinde çalışıyoruz. Ürünlerimiz hazır oldukça burada buluşacağız.', visit:'Ürüne git',
  approachLabel:'03 — NASIL DÜŞÜNÜYORUZ', approachTitle:['Detayda özen.','Deneyimde fark.'], principles:[['Önce insan.','Her şey gerçek bir ihtiyacı anlamakla başlar. Kararlarımızın merkezine ürünü kullanacak insanı koyarız.'],['Daha az karmaşa.','Güçlü teknolojiyi sade bir deneyime dönüştürürüz. Her ayrıntı, işi biraz daha kolaylaştırmak için vardır.'],['Daima bir adım ileri.','Ürünlerimizle birlikte öğreniriz. Geri bildirimleri dinler, düşünür ve geliştirmeye devam ederiz.']],
  closing:'BİR SONRAKİ ADIM, DOĞRU ÜRÜNLE BAŞLAR.', closingTitle:['İhtiyacına uygun','ürünü bul.'], footer:'Gerçek ihtiyaçlar için dijital ürünler.', top:'Başa dön', title:'Odivon — Gerçek ihtiyaçlar için dijital ürünler', description:'Odivon; finans, eğitim, işletme yönetimi ve yaşam alanlarında kullanıma açık dijital ürünler geliştirir.'
 },
 en: {
  lang:'Choose language', nav:'Main navigation', home:'Odivon home', skip:'Skip to content', products:'Products', about:'About Odivon', approach:'Our approach', explore:'Explore products', meet:'Meet Odivon',
  eyebrow:'ONE BRAND. MANY WORLDS. REAL PRODUCTS.', hero:['Better work.','Better days.','Through software.'], intro:'From finance and education to operations and everyday life, Odivon builds working digital products around real needs.', scroll:'KEEP EXPLORING', orbit:'FROM IDEA TO PRODUCT', infinite:'Infinite curiosity.',
  strip:['Start with a real need.','Design a better experience.','Put the product to work.'], aboutLabel:'01 — MEET ODIVON', aboutTitle:['Beyond one industry.','Focused on the need.'], aboutText:'Odivon is a family of software products built for different fields. Each one is shaped around its users and the work they do every day.', aboutNote:'Different fields. Focused products. One Odivon.',
  productLabel:'02 — OUR PRODUCT UNIVERSE', productTitle:['Different worlds.','One signature.'], productText:'Each product focuses on its own problem. All are shaped by the same curiosity and a belief in simple experiences.', soon:'COMING SOON', soonTitle:'The next possibility\nis still being written.', soonText:'We’re working on new ideas. Our products will find their place here as they’re ready.', visit:'Visit product',
  approachLabel:'03 — HOW WE THINK', approachTitle:['Care in the details.','Impact in the experience.'], principles:[['People first.','Everything starts with understanding a real need. We put the people who will use our products at the heart of every decision.'],['Less complexity.','We turn powerful technology into simple experiences. Every detail is there to make things a little easier.'],['Always a step forward.','We learn alongside our products. We listen to feedback, reflect and keep improving.']],
  closing:'THE NEXT STEP STARTS WITH THE RIGHT PRODUCT.', closingTitle:['Find the product','that fits.'], footer:'Digital products for real needs.', top:'Back to top', title:'Odivon — Digital products for real needs', description:'Odivon builds available digital products across finance, education, business operations and everyday life.'
 }
} as const;
export type Locale = keyof typeof messages;
