export const messages = {
 tr: {
  lang:'Dil seçimi', nav:'Ana menü', home:'Odivon ana sayfa', skip:'İçeriğe geç', products:'Ürünler', about:'Odivon hakkında', approach:'Yaklaşımımız', explore:'Ürünleri keşfet', meet:'Odivon’u tanı',
  eyebrow:'BAĞIMSIZ FİKİRLER. ORTAK BİR VİZYON.', hero:['Olasılıkları','yeniden','düşün.'], intro:'İyi bir fikir, her şeyi değiştirebilir. Hayatı ve işi kolaylaştıran dijital ürünlerle o fikri bir adım ileri taşıyoruz.', scroll:'KEŞFETMEYE DEVAM ET', orbit:'FİKİRDEN ÜRÜNE', infinite:'Sınırsız merak.',
  strip:['Merakla düşün.','Cesaretle üret.','Birlikte ilerle.'], aboutLabel:'01 — ODIVON’U TANI', aboutTitle:['Bir sektöre sığmaz.','Bir fikirle başlar.'], aboutText:'Bizim için yazılım, olasılıkları gerçeğe dönüştürmenin yolu. Farklı alanlardaki ihtiyaçları anlıyor, insanların kullanmaktan keyif aldığı dijital ürünler geliştiriyoruz.', aboutNote:'Farklı ürünler. Aynı özen. Tek bir Odivon.',
  productLabel:'02 — ÜRÜN EVRENİ', productTitle:['Farklı dünyalar.','Aynı imza.'], productText:'Her ürün kendi problemine odaklanır. Hepsi aynı merak ve sade bir deneyim anlayışıyla hayat bulur.', soon:'YAKINDA', soonTitle:'Sıradaki olasılık\nhenüz yazılıyor.', soonText:'Yeni fikirler üzerinde çalışıyoruz. Ürünlerimiz hazır oldukça burada buluşacağız.', visit:'Ürüne git',
  approachLabel:'03 — NASIL DÜŞÜNÜYORUZ', approachTitle:['Detayda özen.','Deneyimde fark.'], principles:[['Önce insan.','Her şey gerçek bir ihtiyacı anlamakla başlar. Kararlarımızın merkezine ürünü kullanacak insanı koyarız.'],['Daha az karmaşa.','Güçlü teknolojiyi sade bir deneyime dönüştürürüz. Her ayrıntı, işi biraz daha kolaylaştırmak için vardır.'],['Daima bir adım ileri.','Ürünlerimizle birlikte öğreniriz. Geri bildirimleri dinler, düşünür ve geliştirmeye devam ederiz.']],
  closing:'GELECEK, BİR FİKİR UZAĞINDA.', closingTitle:['Yeni olasılıklara','yer aç.'], footer:'Merakla başlar. Yazılımla hayat bulur.', top:'Başa dön', title:'Odivon — Olasılıkları yeniden düşün', description:'Odivon, farklı ihtiyaçlar için hayatı ve işi kolaylaştıran dijital ürünler geliştirir.'
 },
 en: {
  lang:'Choose language', nav:'Main navigation', home:'Odivon home', skip:'Skip to content', products:'Products', about:'About Odivon', approach:'Our approach', explore:'Explore products', meet:'Meet Odivon',
  eyebrow:'INDEPENDENT IDEAS. A SHARED VISION.', hero:['Rethink','what’s','possible.'], intro:'A good idea can change everything. We take it one step further with digital products that make life and work simpler.', scroll:'KEEP EXPLORING', orbit:'FROM IDEA TO PRODUCT', infinite:'Infinite curiosity.',
  strip:['Think with curiosity.','Build with courage.','Move forward together.'], aboutLabel:'01 — MEET ODIVON', aboutTitle:['Beyond one industry.','It starts with an idea.'], aboutText:'For us, software is a way to turn possibilities into reality. We understand needs across different fields and build digital products people enjoy using.', aboutNote:'Different products. The same care. One Odivon.',
  productLabel:'02 — OUR PRODUCT UNIVERSE', productTitle:['Different worlds.','One signature.'], productText:'Each product focuses on its own problem. All are shaped by the same curiosity and a belief in simple experiences.', soon:'COMING SOON', soonTitle:'The next possibility\nis still being written.', soonText:'We’re working on new ideas. Our products will find their place here as they’re ready.', visit:'Visit product',
  approachLabel:'03 — HOW WE THINK', approachTitle:['Care in the details.','Impact in the experience.'], principles:[['People first.','Everything starts with understanding a real need. We put the people who will use our products at the heart of every decision.'],['Less complexity.','We turn powerful technology into simple experiences. Every detail is there to make things a little easier.'],['Always a step forward.','We learn alongside our products. We listen to feedback, reflect and keep improving.']],
  closing:'THE FUTURE IS AN IDEA AWAY.', closingTitle:['Make room for','new possibilities.'], footer:'Driven by curiosity. Brought to life through software.', top:'Back to top', title:'Odivon — Rethink what’s possible', description:'Odivon builds digital products for different needs, making life and work simpler.'
 }
} as const;
export type Locale = keyof typeof messages;
